# Kitty para MySway: grafito cálido con acento ámbar.
font_family      JetBrains Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.5

foreground       #d8d4c4
background       #202020
selection_foreground #202020
selection_background #d6b36a
cursor           #d6b36a
cursor_text_color #202020

url_color        #82a497
active_border_color #d6b36a
inactive_border_color #575349
bell_border_color #d26b6b

active_tab_foreground #202020
active_tab_background #d6b36a
inactive_tab_foreground #b8b4aa
inactive_tab_background #2a2a2a
tab_bar_background #202020

# Colores ANSI inspirados en la referencia.
color0  #202020
color1  #c96f6f
color2  #83a66f
color3  #d6a84f
color4  #7f9db8
color5  #b58aa5
color6  #82a497
color7  #d8d4c4
color8  #5d5a54
color9  #e07a72
color10 #98b77e
color11 #e2bd6a
color12 #91aec7
color13 #c69ab5
color14 #94b7aa
color15 #f0ead8

window_padding_width 8
background_opacity 0.90
confirm_os_window_close 0
enable_audio_bell no
remember_window_size yes
