for_window [app_id="floating_kitty"] floating enable, move position center, resize set 1000 620
for_window [app_id="pavucontrol"] floating enable, move position center
for_window [app_id="nm-connection-editor"] floating enable, move position center
for_window [app_id="org.kde.kdialog"] floating enable, move position center
for_window [app_id="kdialog"] floating enable, move position center

for_window [app_id="codium"] border pixel 1
for_window [app_id="firefox"] border pixel 1
for_window [app_id="zen-browser"] border pixel 1
for_window [app_id="brave-browser"] border pixel 1
for_window [class="Google-chrome"] border pixel 1
for_window [class="steam"] border pixel 1
